import type { ClickUpTask } from "@/types/clickup";

// Mock data for demo purposes when no API key is configured
export const MOCK_TASKS: ClickUpTask[] = [
  {
    id: "task1", custom_id: null, name: "Redesign da Landing Page", text_content: "Atualizar layout", description: "Redesign completo da landing page do produto", markdown_description: "# Redesign\n\nAtualizar layout e UX da landing page",
    status: { status: "in progress", color: "#4194f6", type: "custom", orderindex: 1 },
    orderindex: "1", date_created: "1711900800000", date_updated: "1714300800000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [
      { id: 101, username: "Ana Silva", email: "ana@test.com", color: "#e91e63", profilePicture: null },
      { id: 102, username: "Carlos Lima", email: "carlos@test.com", color: "#4caf50", profilePicture: null },
    ],
    checklists: [], tags: [{ name: "cliente:Acme Corp", tag_fg: "#fff", tag_bg: "#4194f6" }],
    parent: null, priority: { id: "2", priority: "2", color: "#ffcc00", orderindex: "2" },
    due_date: String(Date.now() + 86400000 * 3), start_date: "1711900800000", points: null,
    time_estimate: 28800000, time_spent: 14400000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "Acme Corp" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task1",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list1", name: "Website", access: true }, project: { id: "proj1", name: "Marketing", hidden: false, access: true },
    folder: { id: "folder1", name: "Marketing", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task2", custom_id: null, name: "API de Integração com Pagamentos", text_content: null, description: "Implementar gateway de pagamento",
    status: { status: "to do", color: "#d3d3d3", type: "open", orderindex: 0 },
    orderindex: "2", date_created: "1712505600000", date_updated: "1714300800000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 103, username: "Bruno Santos", email: "bruno@test.com", color: "#ff9800", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "1", priority: "1", color: "#f50000", orderindex: "1" },
    due_date: String(Date.now() - 86400000 * 2), start_date: null, points: null,
    time_estimate: 57600000, time_spent: 0, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "TechStart" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task2",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list2", name: "Backend", access: true }, project: { id: "proj2", name: "Desenvolvimento", hidden: false, access: true },
    folder: { id: "folder2", name: "Desenvolvimento", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task3", custom_id: null, name: "Campanha Email Marketing Q2", text_content: null, description: "Preparar campanha de email",
    status: { status: "complete", color: "#6bc950", type: "closed", orderindex: 3 },
    orderindex: "3", date_created: "1710691200000", date_updated: "1713283200000", date_closed: "1713283200000", date_done: "1713283200000", archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 104, username: "Diana Costa", email: "diana@test.com", color: "#9c27b0", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "3", priority: "3", color: "#6fddff", orderindex: "3" },
    due_date: "1713283200000", start_date: "1710691200000", points: null,
    time_estimate: 36000000, time_spent: 32400000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "Acme Corp" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task3",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list1", name: "Website", access: true }, project: { id: "proj1", name: "Marketing", hidden: false, access: true },
    folder: { id: "folder1", name: "Marketing", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task4", custom_id: null, name: "Configurar CI/CD Pipeline", text_content: null, description: "Setup GitHub Actions",
    status: { status: "blocked", color: "#f50000", type: "custom", orderindex: 2 },
    orderindex: "4", date_created: "1713888000000", date_updated: "1714300800000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 103, username: "Bruno Santos", email: "bruno@test.com", color: "#ff9800", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "2", priority: "2", color: "#ffcc00", orderindex: "2" },
    due_date: String(Date.now() + 86400000 * 7), start_date: null, points: null,
    time_estimate: 14400000, time_spent: 3600000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "TechStart" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task4",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list3", name: "DevOps", access: true }, project: { id: "proj2", name: "Desenvolvimento", hidden: false, access: true },
    folder: { id: "folder2", name: "Desenvolvimento", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task5", custom_id: null, name: "Documentação da API REST", text_content: null, description: "Swagger docs",
    status: { status: "in progress", color: "#4194f6", type: "custom", orderindex: 1 },
    orderindex: "5", date_created: "1714300800000", date_updated: "1714387200000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 101, username: "Ana Silva", email: "ana@test.com", color: "#e91e63", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "3", priority: "3", color: "#6fddff", orderindex: "3" },
    due_date: String(Date.now() + 86400000 * 5), start_date: null, points: null,
    time_estimate: 21600000, time_spent: 7200000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "GlobalTech" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task5",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list2", name: "Backend", access: true }, project: { id: "proj2", name: "Desenvolvimento", hidden: false, access: true },
    folder: { id: "folder2", name: "Desenvolvimento", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task6", custom_id: null, name: "Testes E2E com Playwright", text_content: null, description: "Implementar testes end-to-end",
    status: { status: "to do", color: "#d3d3d3", type: "open", orderindex: 0 },
    orderindex: "6", date_created: "1714387200000", date_updated: "1714387200000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 102, username: "Carlos Lima", email: "carlos@test.com", color: "#4caf50", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "4", priority: "4", color: "#d8d8d8", orderindex: "4" },
    due_date: String(Date.now() + 86400000 * 14), start_date: null, points: null,
    time_estimate: 43200000, time_spent: 0, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "Acme Corp" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task6",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list3", name: "DevOps", access: true }, project: { id: "proj2", name: "Desenvolvimento", hidden: false, access: true },
    folder: { id: "folder2", name: "Desenvolvimento", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task7", custom_id: null, name: "Design System - Componentes Base", text_content: null, description: "Criar componentes reutilizáveis",
    status: { status: "in progress", color: "#4194f6", type: "custom", orderindex: 1 },
    orderindex: "7", date_created: "1713110400000", date_updated: "1714300800000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [
      { id: 101, username: "Ana Silva", email: "ana@test.com", color: "#e91e63", profilePicture: null },
      { id: 104, username: "Diana Costa", email: "diana@test.com", color: "#9c27b0", profilePicture: null },
    ],
    checklists: [], tags: [], parent: null, priority: { id: "2", priority: "2", color: "#ffcc00", orderindex: "2" },
    due_date: String(Date.now() + 86400000 * 1), start_date: null, points: null,
    time_estimate: 72000000, time_spent: 43200000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "GlobalTech" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task7",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list4", name: "UI/UX", access: true }, project: { id: "proj1", name: "Marketing", hidden: false, access: true },
    folder: { id: "folder1", name: "Marketing", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task8", custom_id: null, name: "Migração Banco de Dados PostgreSQL", text_content: null, description: "Migrar de MySQL para PostgreSQL",
    status: { status: "complete", color: "#6bc950", type: "closed", orderindex: 3 },
    orderindex: "8", date_created: "1710000000000", date_updated: "1712592000000", date_closed: "1712592000000", date_done: "1712592000000", archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 103, username: "Bruno Santos", email: "bruno@test.com", color: "#ff9800", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "1", priority: "1", color: "#f50000", orderindex: "1" },
    due_date: "1712505600000", start_date: "1710000000000", points: null,
    time_estimate: 86400000, time_spent: 79200000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "TechStart" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task8",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list2", name: "Backend", access: true }, project: { id: "proj2", name: "Desenvolvimento", hidden: false, access: true },
    folder: { id: "folder2", name: "Desenvolvimento", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task9", custom_id: null, name: "Otimização de Performance Frontend", text_content: null, description: "Lighthouse score > 90",
    status: { status: "to do", color: "#d3d3d3", type: "open", orderindex: 0 },
    orderindex: "9", date_created: "1714387200000", date_updated: "1714387200000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 102, username: "Carlos Lima", email: "carlos@test.com", color: "#4caf50", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "2", priority: "2", color: "#ffcc00", orderindex: "2" },
    due_date: String(Date.now() + 86400000 * 10), start_date: null, points: null,
    time_estimate: 28800000, time_spent: 0, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "Acme Corp" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task9",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list1", name: "Website", access: true }, project: { id: "proj1", name: "Marketing", hidden: false, access: true },
    folder: { id: "folder1", name: "Marketing", hidden: false, access: true }, space: { id: "space1" },
  },
  {
    id: "task10", custom_id: null, name: "Implementar SSO com OAuth2", text_content: null, description: "Single sign-on para clientes enterprise",
    status: { status: "in review", color: "#a855f7", type: "custom", orderindex: 2 },
    orderindex: "10", date_created: "1713715200000", date_updated: "1714300800000", date_closed: null, date_done: null, archived: false,
    creator: { id: 1, username: "Admin", email: "admin@test.com", color: "#7b68ee", profilePicture: null },
    assignees: [{ id: 103, username: "Bruno Santos", email: "bruno@test.com", color: "#ff9800", profilePicture: null }, { id: 101, username: "Ana Silva", email: "ana@test.com", color: "#e91e63", profilePicture: null }],
    checklists: [], tags: [], parent: null, priority: { id: "1", priority: "1", color: "#f50000", orderindex: "1" },
    due_date: String(Date.now() + 86400000 * 2), start_date: null, points: null,
    time_estimate: 50400000, time_spent: 39600000, custom_fields: [{ id: "cf1", name: "Cliente", type: "text", type_config: {}, value: "GlobalTech" }],
    dependencies: [], linked_tasks: [], team_id: "team1", url: "https://app.clickup.com/t/task10",
    sharing: { public: false, public_share_expires_on: null, public_fields: [], token: null, seo_optimized: false },
    list: { id: "list2", name: "Backend", access: true }, project: { id: "proj2", name: "Desenvolvimento", hidden: false, access: true },
    folder: { id: "folder2", name: "Desenvolvimento", hidden: false, access: true }, space: { id: "space1" },
  },
];
